<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
include_once 'vtlib/Vtiger/Mailer.php';

class Emails_Mailer_Model extends Vtiger_Mailer
{

    public static function getInstance()
    {
        return new self();
    }

    /**
     * Function returns error from phpmailer
     * @return <String>
     */
    function getError()
    {
        return $this->ErrorInfo;
    }

    function initialize()
    {
        parent::initialize();
        $currentUserModel = Users_Record_Model::getCurrentUserModel();
        $userid = $currentUserModel->getId();
        global $adb;
        $result = $adb->pquery("SELECT * FROM vtiger_mail_accounts WHERE user_id=?", Array($userid));
        $smtp = str_replace("imap", "smtp", $adb->query_result($result, 0, 'mail_servername'));
        $username = $adb->query_result($result, 0, 'mail_username');
        $password = $adb->query_result($result, 0, 'mail_password');
        $password = $this->decrypt($password);
        $this->Host = strpos($smtp, "gmail.com") !== false ? "ssl://" . $smtp . ":465" : $smtp;
        $this->Username = $username;
        $this->Password = $password;
        $this->From = $username;
        $this->FromName = $username;

        $CGLE = [
            /*Cebu*/
            "jcogay@channelgrowth.com" => "liam@avefunding.com",
            "jresuena@channelgrowth.com" => "kthompson@avefunding.com",
            "rgana-an@channelgrowth.com" => "taylor.hayes@avefunding.com",
            "mpmanuel@channelgrowth.com" => "summer.johnson@avefunding.com",
            "adubongco@channelgrowth.com" => "adixon@avefunding.com",
            "cbaronda@channelgrowth.com" => "mary.dickenson@avefunding.com",
            "joresuena@channelgrowth.com" => "sandra.thompson@avefunding.com",
            "jtumulak@channelgrowth.com" => "jude.thompson@avefunding.com",

            /*US*/
            "cmora@channelgrowth.com" => "carlos@avefunding.com",
            "hzeledon@channelgrowth.com" => "harold@avefunding.com",
            "clrias@channelgrowth.com" => "charlie@avefunding.com",
            "rcampos@channelgrowth.com" => "richard@avefunding.com",
            "mballadares@channelgrowth.com" => "mario@avefunding.com",
            "emendez@channelgrowth.com" => "eli@avefunding.com",
            "cguerrero@channelgrowth.com" => "carlosg@avefunding.com",
            "mromero@channelgrowth.com" => "manny@avefunding.com"
        ];
        
        if (isset($CGLE[$username])) {
            $this->From = $CGLE[$username];
            $this->FromName = $CGLE[$username];
        }

        if (strpos($smtp, 'office365') !== false) {
            $this->isSMTP();
            $this->isHTML();
            $this->Port = 587;
            $this->SMTPSecure = 'tls';
            $this->SMTPAuth = true;
            $this->SMTPDebug = 1;
            $this->Host = 'smtp.office365.com';
        }
    }

    function reinitialize()
    {
        parent::reinitialize(); // TODO: Change the autogenerated stub
        $this->initialize();
    }

    public function decrypt($value)
    {
        require_once('include/utils/encryption.php');
        $e = new Encryption();
        return $e->decrypt($value);
    }
}
